# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
loader_version=0.16.14
# Mod Properties
mod_version=0.1.6-dev
maven_group=ca.spottedleaf.starlight
archives_base_name=ScalableLux
