# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.3.0-alpha.0
maven_group=ca.spottedleaf.starlight
archives_base_name=ScalableLux-fabric

curseforge_minecraft_versions=26.2
