name: build

on:
  push: {}
  pull_request: {}

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
          java-package: jdk

      - name: setup project
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./build.sh up
          ./build.sh patch

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: never
          cache-provider: basic

      - name: Build
        run: |
          cd ScalableLux-Patched
          ./gradlew clean build --stacktrace

      - name: upload to modrinth and curseforge
        run: |
          cd ScalableLux-Patched
          ./gradlew publishMods
        if: github.ref == 'refs/heads/backports/26.1.2'
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
          GITHUB_EVENT_RAW_PATH: ${{ github.event_path }}
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: 'ScalableLux-Patched/build/libs/*.jar'

